name: CI model dockerhub
  
# Trigger
on:
  push:
    branches:
      - dev

  pull_request:
    branches:
    - dev

# Acciones 
jobs:
  build_docker_images:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo 
        uses: actions/checkout@v2
      
      - name: Login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_MAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image 
        run: docker build -t yorshdock16/datasetapple:v1 .
        
      - name: Docker push to Dockerhub
        run: docker push yorshdock16/datasetapple:v1

      - name: Login into the server
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_MAIL }}' --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: $ {{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login 
            if docker ps --all | grep deploy-datatset; then
              docker stop deploy-dataset
              docker rm deploy-dataset 
            fi 
            
            docker pull ${{ secrets.DOCKER_MAIL }}/datasetapple:v1
            docker run -d --name dataset -p 8000:8000 ${{ secrets.DOCKER_MAIL }}/deploy-dataset:v1
