name: CI model dockerhub
  
# Trigger
on:
  pull_request:
    branches:
    - dev

# Acciones 
jobs:
  build_docker_image:
    runs-on: ubuntu-latest 

    steps:
      - name: Check the repo 
        uses: actions/checkout@v2
      
      - name: Login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_MAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image 
        run: docker build -t yorshdock16/datasetapple:v1 .
        
      - name: Docker push to Dockerhub
        run: docker push yorshdock16/datasetapple:v1
